### ISSUE TITLE
bezier-utils dependency released on Maven Central and github

### ISSUE THREAD

**Issue by acolomitchi** [openimaj/openimaj#101]
Just in case you want to update your dependencies in pom.xml 
groupId: com.caffeineowl
artifactId: bezier-utils

The 1.0.0-RELEASE version is the maven-ized version of the library on the caffeineowl.com site with no other changes.

The github location: https://github.com/acolomitchi/bezier-utils

Thanks,

acolomitchi

**Comment by jonhare** [comment]
Done. Many thanks - that's one less dependency to manage manually :)
