### ISSUE TITLE
Cannot resolve maven dependencies

### ISSUE THREAD

**Issue by BorisWiegand** [openimaj/openimaj#102]
If I include 
		<dependency>
			<groupId>org.openimaj</groupId>
			<artifactId>core</artifactId>
			<version>1.3.1</version>
			<scope>compile</scope>
		</dependency>
in my Maven POM I get following errors:

[WARNING] The POM for org.jbibtex:jbibtex:jar:r16 is missing, no dependency information available
[WARNING] The POM for vigna.dsi.unimi.it:jal:jar:20031117 is missing, no dependency information available

**Comment by jonhare** [comment]
Add http://maven.openimaj.org as a repository (see e.g. http://www.mkyong.com/maven/how-to-add-remote-repository-in-maven-pom-xml/ for an example) & it should work.

**Comment by BorisWiegand** [comment]
Thank you for your quick answer. I will try at the weekend and inform you if it works. 
Am 25.04.2016 22:46 schrieb Jonathon Hare <notifications@github.com>:Add http://maven.openimaj.org as a repository (see e.g. http://www.mkyong.com/maven/how-to-add-remote-repository-in-maven-pom-xml/ for an example) & it should work.

**Comment by BorisWiegand** [comment]
Hi Jonathan,

thank you very much for your help. The error was a wrong mirror 
configuration in my settings.xml

Regards

Boris

Am 25.04.2016 um 22:46 schrieb Jonathon Hare:
> Add http://maven.openimaj.org as a repository (see e.g. 
> http://www.mkyong.com/maven/how-to-add-remote-repository-in-maven-pom-xml/ 
> for an example) & it should work.
>
>
>
