### ISSUE TITLE
Can we get a new release on Maven Central?

### ISSUE THREAD

**Issue by timmolter** [openimaj/openimaj#107]
The last one is 1.3.1 from 2014.

**Comment by jonhare** [comment]
Working on it now. Bear with...

**Comment by jonhare** [comment]
Ok, it's in the OSSRH releases repo (e.g. https://oss.sonatype.org/content/repositories/releases/org/openimaj/content/animation/1.3.5/), but it can take up to a couple of hours to sync with central. 

I've also added some notes on how releases are made & included the instructions for releasing to central in commit 229b3a80bc7f5e050ee8078355fb01fa72297d5e. Hopefully this will mean I don't forget to do this next time :)
