### ISSUE TITLE
Unresolved dependency: net.billylieurance.azuresearch:azure-bing-search-java:0.12.0

### ISSUE THREAD

**Issue by mrvisser** [openimaj/openimaj#108]
I have the resolver in my build.sbt:

`"OpenIMAJ Maven Repo" at "http://maven.openimaj.org"`

It used to work.

Looking in the maven repository, it looks like the pom is a directory and not an xml file:

http://maven.ecs.soton.ac.uk/content/groups/maven.openimaj.org/net/billylieurance/azuresearch/azure-bing-search-java/0.12.0/

0.13.0's pom looks correct.

**Comment by jonhare** [comment]
I think this is now fixed - it seems someone was publishing a broken maven repo that took precedence over the official one for those jars in the maven.openimaj.org proxy. Please reopen this if you still have problems.

**Comment by DCRussianDev** [comment]
Looks like this is an issue again, the main URL (http://maven.openimaj.org/net/billylieurance/azuresearch/azure-bing-search-java/0.12.0/azure-bing-search-java-0.12.0.pom) ends up resolving to (http://maven.openimaj.org/nexus/content/groups/maven.openimaj.org/net/billylieurance/azuresearch/azure-bing-search-java/0.12.0/azure-bing-search-java-0.12.0.pom/)

**Comment by jonhare** [comment]
Seems to be working now? I tweaked the order of mirrored repos in nexus to fix it. In the long-term this should be less of an issue for openimaj as that dependency is no longer used in the latest snapshots (primarily due to it not actually working with the modern Azure API).

**Comment by DCRussianDev** [comment]
Yep, all good now and thanks for the long-term info, sounds good.
