### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by adamw** [openimaj/openimaj#109]
There's no `LICENSE` file in the repo. The website links to a "BSD-style license", but the link is broken (http://openimaj.org/license.html). It would be good to know when it's possible to use the library :)

**Comment by jonhare** [comment]
Gah, something broke when I moved the site from sourceforge to github that resulted in the license link breaking. Fixed now. I've added a top-level LICENSE file, however please note that a a few (probably no more than two of the sub-modules have different conditions - FaceTracker is one that springs to mind). Every module has a COPYING file that precisely lays out the terms.

**Comment by adamw** [comment]
Thanks! :)
