### ISSUE TITLE
no/uib/cipr/matrix/NotConvergedException not found

### ISSUE THREAD

**Issue by stefan-reich** [openimaj/openimaj#110]
java.lang.NoClassDefFoundError: no/uib/cipr/matrix/NotConvergedException
    at org.openimaj.image.processing.convolution.FConvolution.setup(FConvolution.java:182)
    at org.openimaj.image.processing.convolution.FConvolution.<init>(FConvolution.java:148)

I am, essentially, using the latest source from GitHub. Where is that class?

Example code although it probably doesn't matter in this case :-) : http://tinybrain.de/1004907

Please fix, I really want to use your tool... :-) Thanks

Edit: OK, I hotfixed it for me by including [this](www.java2s.com/Code/Jar/m/Downloadmtj0913jar.htm). Probably not the cleanest way? Anyway, I get a [nice edge detection](http://tinybrain.de/1004921) now. :-)

**Comment by jonhare** [comment]
Not sure how you are managing the dependencies? Use maven or similar and let the tools do the work for you - trying to manually manage them will cause many issues.
