### ISSUE TITLE
MultiBandImage#add( T ) contains infinite loop

### ISSUE THREAD

**Issue by sp16g14** [openimaj/openimaj#112]
The method calls itself on line 133

    final I newImage = this.clone();
    newImage.add(num);
    return newImage;

**Comment by jonhare** [comment]
Fixed in 619d146c74035ab530bd297d2159867bbae1a02f. Interestingly I guess no one has ever tried to add (or subtract or divide) a multi band image by a scalar before (not that it would be a common operation)...

Thanks for reporting :)
