### ISSUE TITLE
The import org.openimaj.util.array.ArrayUtils cannot be resolved

### ISSUE THREAD

**Issue by donaldlee2008** [openimaj/openimaj#113]
The import org.openimaj.util.array.ArrayUtils cannot be resolved
there is no ArrayUtils.java in this package

**Comment by jonhare** [comment]
Sure there is - its automatically generated from core/core/src/main/jtemp/org/openimaj/util/array/ArrayUtils.jtemp as part of the maven build using the jtemp templating library. There are hundreds of other classes that are built in the same way.

What are you attempting to do? If you just want to use OpenIMAJ, you should just add the precompiled jars from the maven repo to your project using your favourite dependency management tool.
