### ISSUE TITLE
Question: How did you compile all the native libs?

### ISSUE THREAD

**Issue by timmolter** [openimaj/openimaj#114]
Sorry to highjack this issues board. I used your library in the past and am building a different library requiring JNI. Did you compile the native lib files each on a separate system or can you for example build the Linux, Windows, and Mac libs  all on a Mac or Linux? Much appreciated!

**Comment by jonhare** [comment]
Originally different physical machines for each OS; last few times they were built we used a set of virtual machines. Theoretically cross compiling might be possible, but its probably not worth the effort.

**Comment by timmolter** [comment]
Thank you very much for the tip!
