### ISSUE TITLE
OpenIMAJ library cannot read tiff files even with 3rd party libraries?

### ISSUE THREAD

**Issue by mosab-shaheen** [openimaj/openimaj#119]
The library, I think, contains a bug regarding reading TIFF files.  Even if you use 3rd party libraries like "TwelveMonkeys" for some files it is causing an error.

I raised a question on stackoverflow. Could you please check it:
http://stackoverflow.com/questions/42623770/openimaj-library-cannot-read-tiff-files

**Comment by mosab-shaheen** [comment]
This is the tiff file (GeoTiff specifically) that I am using which causes the error :

"https://drive.google.com/file/d/0ByKaCojxzNa9MWxPTUJjZURHR1E/view?usp=sharing"

**Comment by jonhare** [comment]
OK, with that image and the change in bc8ebab, image loading now works. The maven snapshot now contains this fix. I'll close this issue now, but reopen if you run into other problem images.
