### ISSUE TITLE
Retrieving images from database for face recognition

### ISSUE THREAD

**Issue by ghostidentity** [openimaj/openimaj#120]
Hello,

I'd like to retrieve images in database for face recognition but I cant find any sample to try.
I do tried the VFDGroupdataset but it process images inside the archived file.

Do you have one ? 

Thanks,
Mark

**Comment by jonhare** [comment]
I'm not really sure what you're asking for? Can you try and clarify exactly what you need?

**Comment by ghostidentity** [comment]
Yeah, i mean to say retrieve the images from actual RDMS.

**Comment by ghostidentity** [comment]
Hello jon, pls close this issue.  I already figured how to do it.
