### ISSUE TITLE
Issue with Tutorial - Getting Started

### ISSUE THREAD

**Issue by nusynergi** [openimaj/openimaj#122]
http://openimaj.org/tutorial/getting-started-with-openimaj-using-maven.html

Looking at the work done in OpenImaj and it is very impressive.
I have followed the steps on the above web page with maven but it defaults to using an internal Maven catalog. 
I run the following command >

`OpenIMAJ user_bd$ mvn -DarchetypeCatalog=http://maven.openimaj.org/archetype-catalog.xml archetype:generate
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:3.0.0:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:3.0.0:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] --- maven-archetype-plugin:3.0.0:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] No catalog defined. Using internal catalog
[INFO] No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)
`

Can someone point me in the right direction please

**Comment by jonhare** [comment]
The first problem is a result of a change in the archetype plugin: https://issues.apache.org/jira/browse/ARCHETYPE-519

Easiest workaround is to revert to version 2.2 of the plugin:

    mvn -DarchetypeCatalog=http://maven.openimaj.org/archetype-catalog.xml org.apache.maven.plugins:maven-archetype-plugin:2.4:generate

**Comment by nusynergi** [comment]
Thanks for the quick reply Jon. I tried the following: -

`mvn -DarchetypeCatalog=http://maven.openimaj.org/archetype-catalog.xml org.apache.maven.plugins:maven-archetype-plugin:2.4:generate`

I got 

`[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:2.4:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:2.4:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] --- maven-archetype-plugin:2.4:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)`

I changed the URL to reflect v 2.2 vs 2.4

`mvn -DarchetypeCatalog=http://maven.openimaj.org/archetype-catalog.xml org.apache.maven.plugins:maven-archetype-plugin:2.2:generate`

I got 

`OpenIMAJ User_A$ mvn -DarchetypeCatalog=http://maven.openimaj.org/archetype-catalog.xml org.apache.maven.plugins:maven-archetype-plugin:2.2:generate
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:2.2:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:2.2:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] --- maven-archetype-plugin:2.2:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)`

So not sure if I missed something here? Is it my version on Maven?

**Comment by jonhare** [comment]
Did it not ask you to make a choice of archetype following that? Here's what I get: 

```sh
bart:~ jsh2$ mvn -DarchetypeCatalog=http://maven.openimaj.org/archetype-catalog.xml org.apache.maven.plugins:maven-archetype-plugin:2.4:generate
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:2.4:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:2.4:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] --- maven-archetype-plugin:2.4:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)
Choose archetype:
1: http://maven.openimaj.org/archetype-catalog.xml -> org.apache.tapestry:quickstart (-)
2: http://maven.openimaj.org/archetype-catalog.xml -> org.apache.maven.archetypes:maven-archetype-webapp (An archetype which contains a sample Maven Webapp project.)
3: http://maven.openimaj.org/archetype-catalog.xml -> org.apache.maven.archetypes:maven-archetype-quickstart (An archetype which contains a sample Maven project.)
4: http://maven.openimaj.org/archetype-catalog.xml -> org.hibernate:hibernate-validator-quickstart-archetype (-)
5: http://maven.openimaj.org/archetype-catalog.xml -> org.codehaus.mojo.archetypes:netbeans-platform-app-archetype (Archetype for sample application based on NetBeans Platform. Creates parent POM with branding and empty NBM project.)
6: http://maven.openimaj.org/archetype-catalog.xml -> org.glassfish.jersey.archetypes:jersey-quickstart-grizzly2 (An archetype which contains a quick start Jersey project based on Grizzly container.)
7: http://maven.openimaj.org/archetype-catalog.xml -> io.fabric8.archetypes:springboot-activemq-archetype (Creates a new Shows how to use ActiveMQ with Spring Boot in the Java Container)
8: http://maven.openimaj.org/archetype-catalog.xml -> org.scala-tools.archetypes:scala-archetype-simple (-)
9: http://maven.openimaj.org/archetype-catalog.xml -> org.openimaj:openimaj-subproject-archetype (Maven archetype for creating OpenIMAJ subprojects with the most of the standard configuration completed automatically)
10: http://maven.openimaj.org/archetype-catalog.xml -> org.openimaj:openimaj-quickstart-archetype (Maven quickstart archetype for OpenIMAJ)
11: http://maven.openimaj.org/archetype-catalog.xml -> com.alibaba.citrus.sample:archetype-webx-quickstart (-)
12: http://maven.openimaj.org/archetype-catalog.xml -> am.ik.archetype:maven-reactjs-blank-archetype (Blank Project for React.js)
13: http://maven.openimaj.org/archetype-catalog.xml -> org.springframework.osgi:spring-osgi-bundle-archetype (Spring OSGi Maven2 Archetype)
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): 3:
```

**Comment by nusynergi** [comment]
Yes. My bad. I was hung up on the fact it was saying 'No archetype defined'. Apologies. Pretty new to this stuff tbh, I'm an C# guy usually. Which is best option for the tutorials?

**Comment by nusynergi** [comment]
Yes. My Bad. Im a C# guy usually. Pretty new to this stuff. Apologies. I will choose option 10.

**Comment by jonhare** [comment]
Just check that your option 10 is the same as mine! I'm not sure if you'll get a different order! You need the one that says `http://maven.openimaj.org/archetype-catalog.xml -> org.openimaj:openimaj-quickstart-archetype (Maven quickstart archetype for OpenIMAJ)`. 

(These archetypes are basically just "initial' empty projects from which you start building your own code; each one will have a different set of starter files and dependencies declared based on what kind of project the the archetype is designed for)

**Comment by nusynergi** [comment]
Yes they match. Thanks. 

`10: http://maven.openimaj.org/archetype-catalog.xml -> org.openimaj:openimaj-quickstart-archetype (Maven quickstart archetype for OpenIMAJ)`

I then followed the steps as you lay out at : -

http://openimaj.org/tutorial/getting-started-with-openimaj-using-maven.html

It downloaded a lot of files. I'm guessing the entire dependency list. 

It completed with 

`INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:39 min
[INFO] Finished at: 2017-03-24T11:24:08+00:00
[INFO] Final Memory: 140M/1399M
[INFO] ------------------------------------------------------------------------`

Can I use IntelliJ with this project now?

**Comment by jonhare** [comment]
Yes, I don't use IntelliJ, but in theory you just load or import the project that was just created & it should just work...

**Comment by nusynergi** [comment]
Worked a treat. For anyone using IntelliJ here is the simple steps

Open IntelliJ
File > New > Project from Existing Sources
Build > Build Project
Run > Run... (Select 'App')

**Comment by nusynergi** [comment]
Hi Jon,

Many thanks for the help earlier this year. Was much appreciated.

I have been experimenting with you OpenImaj implementation of SIFT and was wondering what the legal stand point on using it in commercial applications was. From research it appears there is a patent against this algorithm. I understand this is not the case in Europe (I could be wrong), but just wondered if your implementation aligned to this patented version? If so, do you have any other similar approach such as BRISK or AKAZE which may fit the bill….

FYI I am trying to build a library of known images and store their descriptors (not the images) in memory / serialized objects. I can then search an inbound image for the presence of these stored images very rapidly. Any ideas on how this could be done would be great.

Regards

Ben



This email message (including attachments) is CONFIDENTIAL and intended for the addressee(s) only, and may be legally privileged. If you are not the intended recipient, please notify the author and please delete this email immediately in its entirety and not read, copied or disclosed to anyone else.

Internet communications cannot be guaranteed to be timely, secure, error or virus free. Although we make every effort to make sure that data is virus free, “NuSyenrgi Ltd” cannot guarantee the security of any data outside of our own computer systems and therefore advises recipient companies to carry out their own virus checks.

NuSynergi Ltd - Registered in England and Wales with company number : 10112110
