### ISSUE TITLE
Use of IntelliJ and OpenImaj missing method issue

### ISSUE THREAD

**Issue by nusynergi** [openimaj/openimaj#123]
As I was unable to build the project using Maven and this URL :  -

[](http://maven.openimaj.org/archetype-catalog.xml archetype:generate)

I therefore decided to try and use Maven within IntelliJ and build my own project.

I followed the steps here to get all the Compile dependencies : -

http://openimaj.org/openimaj-image/image-processing/dependencies.html

I was able to finish the first tutorial, but have an issue trying to build the example here : -

http://openimaj.org/tutorial/introduction-to-clustering-segmentation-and-connected-components.html

I get an issue when I run this : -

`FloatCentroidsResult result = cluster.cluster(imageData);`

I believe is a dependency issue. Here is the error : -

`Exception in thread "main" java.lang.NoSuchMethodError: org.openimaj.data.DataSource.size()I
	at org.openimaj.ml.clustering.kmeans.FloatKMeans.cluster(FloatKMeans.java:261)
	at org.openimaj.ml.clustering.kmeans.FloatKMeans.cluster(FloatKMeans.java:242)
	at org.openimaj.ml.clustering.kmeans.FloatKMeans.cluster(FloatKMeans.java:210)
	at Image.main(Image.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`

Inside of FloatKMeans it points to data.size() .

`    protected void cluster(DataSource<float[]> data, FloatKMeans.Result result) throws Exception {
        float[][] centroids = result.centroids;
        int K = centroids.length;
        int D = centroids[0].length;
        int N = data.size();` 

Can someone tell me what I am missing from Maven in order to execute this?

Many thanks

**Comment by jonhare** [comment]
Gah, it seems the first problem is a result of a change in the archetype plugin: https://issues.apache.org/jira/browse/ARCHETYPE-519

You'll need to add additional dependencies manually. This is the full list from the archetype, but feel free to pick and choose based on what your doing:

    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>audio-processing</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>demos</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>core-hadoop</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>faces</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>image-annotation</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>image-feature-extraction</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>image-local-features</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>image-processing</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>clustering</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>nearest-neighbour</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>klt-tracker</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>video-processing</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>xuggle-video</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>common-stream</artifactId>
      <version>${openimaj.version}</version>
      <scope>compile</scope>
    </dependency>

**Comment by nusynergi** [comment]
<dependency>
  <groupId>org.openimaj</groupId>
  <artifactId>image-feature-extraction</artifactId>
  <version>${openimaj.version}</version>
  <scope>compile</scope>
</dependency>

Still the same issue

**Comment by nusynergi** [comment]
Please see this thread for the way to work with IntelliJ

https://github.com/openimaj/openimaj/issues/122#issuecomment-288996405
