### ISSUE TITLE
Wrong scaling after closing a polygon

### ISSUE THREAD

**Issue by ballaminut** [openimaj/openimaj#126]
Closing a polygon inserts at the end of the vertices list a reference to the first vertex; scaling go through all vertices and updates them, thus updating the first vertex twice.

Here is an example of unit test

    float distance = 10.0f;
    float factor = 1.5f;
    Polygon polygon = new Polygon();
    polygon.addVertex(-distance, -distance);
    polygon.addVertex(-distance, distance);
    polygon.addVertex(distance, distance);
    polygon.addVertex(distance, -distance);
    polygon.close();
    polygon.scale(factor);
    List<Point2d> vertices = polygon.getVertices();
    for (Point2d vertex : vertices) {
      assertEquals(distance * factor, Math.abs(vertex.getX()), 0.1);
      assertEquals(distance * factor, Math.abs(vertex.getY()), 0.1);
    }

**Comment by jonhare** [comment]
Good catch - thank you! Should be fixed in 919aef3d1a877ece1e4d09256b166d9825c91171
