### ISSUE TITLE
Warp Face Model

### ISSUE THREAD

**Issue by msj121** [openimaj/openimaj#128]
First, great library!

Is there an approach where I can use org.openimaj.demos.faces.ModelManipulatorGUI to not only manipulate the model, but also the image that the model represents.

Meaning, assuming I move/affect one point of the model, I want it to affect the picture as well. Is there a way of doing this? Currently I can't figure it out. I can use the PiecewiseMeshWarp; however, than I need to paste it back onto the original image, like in MultiPuppeteer.

Thank you for any advice/help!

**Comment by jonhare** [comment]
I think you mean something like this? https://gist.github.com/jonhare/83a714728e611feecadbbb31766f8cfd

(apologies for the messy code - I just quickly hacked this into a copy of ModelManipulatorGUI. The key bits are in the `ModelView#paint` method and the `ModelManipulatorGUI2` constructor. The former warps the face image to match the model using a `PiecewiseMeshWarp` & the latter loads the image and fits a model to it). If your original image had a background you wanted to maintain, then doing something like in the `composite` method in `MultiPuppeteer` would let you draw the new face on top of the original image.

**Comment by msj121** [comment]
So I understand how to change this to manipulate the actual webcam image, but is there a way to use the PiecewiseMeshWarp and include the background of the image with it. 

The reason I ask is simply because when I "paste" the manipulated image back onto the same image you can see where it doesn't line up. I would prefer the image be slight deformed than a hard line.

I have tried adding triangles for the top left, right etc... but I only get a diagonal line through the picture, which confuses me.

```
                MBFImage source = (get webcam image....);
                Point2d topLeft = source.getBounds().getTopLeft();
		Point2d bottomRight = source.getBounds().getBottomRight();
		Point2d centre = source.getBounds().calculateCentroid();
		Point2d topRight = bottomRight.copy();
		topRight.setY(0);
		Point2d bottomLeft = bottomRight.copy();
		topRight.setX(0);
		Triangle top = new Triangle(topLeft,topRight,centre);
		Triangle right = new Triangle(topRight,bottomRight,centre);
		Triangle leftTriangle = new Triangle(topLeft,topRight,bottomLeft);
		Triangle rightTriangle = new Triangle(topRight,bottomRight,bottomLeft);
		matches.add(new Pair<Shape>(top.clone(),top.clone()));
		matches.add(new Pair<Shape>(right.clone(),right.clone()));
		matches.add(new Pair<Shape>(leftTriangle.clone(),leftTriangle.clone()));
		matches.add(new Pair<Shape>(rightTriangle.clone(),rightTriangle.clone()));
```

**Comment by msj121** [comment]
Okay, I looked at PiecewiseMeshWarpDemo, and used their points and now I get the background, but sadly, it is the same as pasting the new on the old.

I guess I have to take the transformed face and then figure out the triangles in the remaining background to add to the PiecewiseMeshWarp and not the entire background split into 4 around the centre like the demo.

Tricky. Fun :).
