### ISSUE TITLE
Replace Background Green Screen with Image

### ISSUE THREAD

**Issue by msj121** [openimaj/openimaj#129]
Hi,
  I can run the BackgroundSubtract code to hide the bakground, but I want to use a green screen and replace the background with an image. Is there any code or idea how to do this?

Thanks.

**Comment by msj121** [comment]
Currently just doing it by pixel, checking if its green. Is there a better way?

**Comment by jonhare** [comment]
Pixel-wise is probably the fastest way. I guess you could also compute super-pixels (e.g. using a clustering method or connected components) and do it on a super-pixel basis...
