### ISSUE TITLE
LocalContrastFilter is broken

### ISSUE THREAD

**Issue by limstepf** [openimaj/openimaj#131]
[LocalContrastFilter](https://github.com/openimaj/openimaj/blob/master/image/image-processing/src/main/java/org/openimaj/image/processing/algorithm/LocalContrastFilter.java) is currently (well, at least since 3 years) broken, and always returns a zeroed image.

Line 74: `min = Math.min(min, image.pixels[yy][xx]);`
Line 75: `max = Math.min(min, image.pixels[yy][xx]);`

Guess that's a typical "copy and paste" bug; clearly line 75 should read: 

Line 75: `max = Math.max(max, image.pixels[yy][xx]);`

This bug also affects one other class/algorithm, namely: [AdaptiveLocalThresholdBernsen](https://github.com/openimaj/openimaj/blob/master/image/image-processing/src/main/java/org/openimaj/image/processing/threshold/AdaptiveLocalThresholdBernsen.java).
Pull request: [https://github.com/openimaj/openimaj/pull/132](https://github.com/openimaj/openimaj/pull/132)

**Comment by jonhare** [comment]
Fixed - thanks for the PR :)
