### ISSUE TITLE
Face detection: get info on the orientation of the detected face?

### ISSUE THREAD

**Issue by spamrefuse** [openimaj/openimaj#133]
The tutorial has information on face detection in a video, but can OpenIMAJ also detect in what direction the faces are looking?
In othter words: detect the orientation of a face.
R.

**Comment by jonhare** [comment]
Yes (within reason) if you use the `CLMFaceDetector` - the returned `CLMDetectedFace` instances have methods to get the roll, pitch and yaw of the faces.
