### ISSUE TITLE
Build Error v. 13.6

### ISSUE THREAD

**Issue by shakerb** [openimaj/openimaj#144]
I downloaded the zipped source files for  version 1.3.6 and  attempted to build it with Apache Maven 3.5.2 + Java version: 1.8.0_144. The build failed with error: 

> _http\://maven.openimaj.org/.error=Could not transfer **artifact com.sun.media\:jai-codec\:jar\:1.1.3** from/to openimaj-maven (http\://maven.openimaj.org/)\: GET request of\: com/sun/media/jai-codec/1.1.3/jai-codec-1.1.3.jar from openimaj-maven failed_

The issue is probably due to the non-availability of the quoted artifact at either of the standard repositories,  `<id>openimaj-maven</id>` and `<id>openimaj-snapshots-maven</id>` included in the project pom. After I added the third party repository noted at Maven Central for this artifact -  `<url>https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/</url>` - the build completed successfully.  My locally cached artifacts appear to test successfully in Eclipse IDE.

As a newbie to openimaj, and I apologize if the issue has already been tracked. Thank you for your attention.

**Comment by jonhare** [comment]
I'm not sure why you saw that - if you look here, you'll see the openimaj maven repo has that jar: http://maven.openimaj.org/com/sun/media/jai-codec/1.1.3/

It might have just been a temporary network glitch...

**Comment by shakerb** [comment]
Yes, it seems so. I was able to build it successfully today without reference to the third party repository at `<url>https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/</url>`. Thank you for the quick response.
