### ISSUE TITLE
How to use MedianFilter class

### ISSUE THREAD

**Issue by xuesongle** [openimaj/openimaj#145]
Hi, I am trying to apply MedianFilter after thresholding with the following code.

FImage th = threshold(img,thValue);
Set<Pixel> support = new HashSet<Pixel>();
MedianFilter noiseF = new MedianFilter(support);
FImage nfTh = th.clone();
noiseF.processImage(nfTh);

I know the problem exists in 2nd line where a set of support is not provided appropriately but not sure what is right way to apply MedianFilter here.

Could someone give me some example as I have not found any example online yet? Thanks in advance.

**Comment by jonhare** [comment]
As per the API docs, the support is the set of pixels (with coordinates relative to the current pixel) that will be used to compute the median; for example, if you wanted a 3x3 block centred around the current pixel you would use coordinates (-1,-1), (0,-1), (1,-1), (-1, 0), (0,0), (1,0), (-1,1), (0,1), and (1,1).

Obviously in reality specifying these manually for simple or common filters would be a pain - the `FilterSupport` class (http://openimaj.org/apidocs/org/openimaj/image/processing/algorithm/FilterSupport.html) is here to help & contains predefined 3x3 block and cross supports, as well as a method to build block supports of a size that you specify.

**Comment by xuesongle** [comment]
Thanks for your tip again. jonhare. It is much clear now.
