### ISSUE TITLE
Old version dependencies

### ISSUE THREAD

**Issue by andresBelAlonso** [openimaj/openimaj#149]
Hi, 
Cleaning dependencies conflicts on my company's project I found  that OpenImaj has many outdated dependencies. I list here the outdated libs that I found : 

From core project : 

- GroupId : org.apache.httpcomponents
 ArtifactId :  httpclient 
 Used version : 4.5, 
 Last version : 4.5.6

- GroupId : uk.com.robust-it
 ArtifactId :  cloning 
 Used version : 1.9.1, 
 Last version : 1.9.10

- GroupId : commons-io
 ArtifactId :  commons-io
 Used version : 2.2, 
 Last version : 2.6

- GroupId : com.google.guava
 ArtifactId :  guava
 Used version : 14.0.1, 
 Last version : 25.1-jre

- GroupId : org.objenesis
 ArtifactId :  objenesis
 Used version : 2.2, 
 Last version : 2.6

- GroupId : log4j
 ArfifactId : log4j
 Used version : 1.2.14
Last version : Use instead this dependency:  (log4j artifact was displace to org.apache.logging.log4j)

> <dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>2.11.0</version>
</dependency>

In core-experiment project : 

- GroupId : net.sf.jasperreports
 ArtifactId :  jasperreports
 Used version : 4.6.0, 
 Last version : 6.6.0

- GroupId : log4j
 ArfifactId : log4j
 Used version : 1.2.14
Last version : Use instead this dependency:  (log4j artifact was displace to org.apache.logging.log4j)

> <dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>2.11.0</version>
</dependency>

In core-image project : 

- GroupId : com.twelvemonkeys.imageio
 ArtifactId :  imageio-core
 Used version : 3.1.1, 
 Last version : 3.3.2 (This version conflict created me a lot a problems, change also imageio-jpeg artifact) 

- GroupId : com.twelvemonkeys.common
 ArtifactId :  common-lang
 Used version : 3.1.1, 
 Last version : 3.3.2 

I hope that this issue will improve the project. 
Thank you for your great work and documentation.

**Comment by jonhare** [comment]
Ok, this should all be resolved (879e882297e06e3458363e910b422ab4ae48780f introduced a missing dependency required to compile). Updating to log4j2 required a few code changes, but everything else seemed to use the same API. All unit tests run, so I'm assuming we haven't broken anything.

**Comment by jonhare** [comment]
p.s. thanks for providing the list of updates :)
