### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by changbaishan** [openimaj/openimaj#151]
When I execute  "mvn assembly:assembly" according to instruction, here is what I got:

[ERROR] Failed to execute goal on project openimaj-test-project: Could not resolve dependencies for project uk.ac.soton.ecs.jsh2:openimaj-test-project:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.openimaj:demos:jar:1.3.7, org.openimaj:core-hadoop:jar:1.3.7, org.openimaj:common-stream:jar:1.3.7: Could not find artifact org.openimaj:demos:jar:1.3.7 in openimaj-maven (http://maven.openimaj.org/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jonhare** [comment]
Hang tight - we're halfway through the release of a new version. Either change to version 1.3.6 or wait a bit so we can get all the jars deployed.

**Comment by changbaishan** [comment]
Thanks very much, Dr. Hare.


I'll hang tight as instructed but still anxious to build.


Best regards,


Yong

________________________________

**Comment by jonhare** [comment]
1.3.7 should now be fully released.

**Comment by jonhare** [comment]
That problem will go away if you update java to 8u121 or later. You can skip javadoc compilation with `-Dmaven.javadoc.skip=true` though. 

All that being said, there is little reason to try compiling OpenIMAJ from source unless you want to make changes to it. If you want to build something using the library, all the release jars are in maven central - just follow the instructions in the tutorial (http://openimaj.org/tutorial/getting-started-with-openimaj-using-maven.html) to setup a maven project that includes them automatically.

**Comment by changbaishan** [comment]
Dear Dr. Hare,


Thank you for your help.


Following your instructions, I am using jars from mvn central to learn OpenIMAJ. I am totally attracted by this software. The objects design is just what they need to be.   Object oriented is not enough, only right objects help you doing things. Having said that, I am just at "processing your first image" stage. In the future, I hope I can get your further help.


Best regards,


Yong Liu

________________________________
