### ISSUE TITLE
Rebuild FImageGradients

### ISSUE THREAD

**Issue by changbaishan** [openimaj/openimaj#152]
Exception in thread "main" java.lang.NoClassDefFoundError: odk/lang/FastMath has been a recurring issue. I run into this issue when using DoFSIFTEngine. 

What is missing is a JAFAMA-jar (See issue 26).  This is precisely why a rebuild is necessary. odk/lang/FastMath is from a staled jar. The JAFAMA-jar as found in sourceforge.net changed structured. Even if I include the new JAFAMA-jar, java.lang.NoClassDefFoundError still persist.

Would Dr. Hare please use the new  JAFAMA-jar to rebuild openimaj image? Or release the JAFAMA-jar he is using? As I see it, use of openimaj hit a ceiling with this issue.

Thank you for your attention.

**Comment by jonhare** [comment]
The correct jar is here: http://maven.openimaj.org/net/sf/jafama/JaFaMa/1.2/JaFaMa-1.2.jar

There are a number of dependency jars not in maven central which can only be downloaded from the openimaj maven repository - there isn't all that much we can do about that as we didn't develop them. We can look at updating JaFaMa, but you will likely still run into other dependency problems. 

If you've imported openimaj dependencies into a maven pom that wasn't created with the openimaj quickstart archetype you'll need to add:

```
<repositories>
    <repository>
      <id>openimaj-maven</id>
      <url>http://maven.openimaj.org/</url>
    </repository>
</repositories>
```

to your pom.xml (the openimaj quickstart archetype purposefully does this for you). If you're running a local maven proxy you'll need to configure it (see https://sourceforge.net/p/openimaj/discussion/general/thread/817822cd/)

**Comment by changbaishan** [comment]
Resolved
