### ISSUE TITLE
Use colt jal.objects.BinaryPredicate to replace the existing JAL library

### ISSUE THREAD

**Issue by changbaishan** [openimaj/openimaj#153]
There is a jal.objects.BinaryPredicate object in colt. And colt is in my class path. However, I still have this error:

Exception in thread "main" java.lang.NoClassDefFoundError: jal/objects/BinaryPredicate
	at org.openimaj.knn.approximate.ByteNearestNeighboursKDTree.<init>(ByteNearestNeighboursKDTree.java:125)
	at org.openimaj.feature.local.matcher.FastBasicKeypointMatcher.setModelFeatures(FastBasicKeypointMatcher.java:134)
	at org.openimaj.feature.local.matcher.consistent.ConsistentLocalFeatureMatcher2d.setModelFeatures(ConsistentLocalFeatureMatcher2d.java:156)
	at imaj.ImajTester.main(ImajTester.java:186)

Presumably, the jal.objects.BinaryPredicate belongs to a JAL library. Is it possible that Dr. Hare release where to find this jar? And if it is not a jar, Is there a java work around?

Thanks very much.

**Comment by changbaishan** [comment]
Thank you very much. Dr. Hare.

Here was the code I used:
		try {
			MBFImage query = ImageUtilities.readMBF(new URL("https://pbs.twimg.com/media/Dpubr7DUcAArhC5.jpg"));
			MBFImage target = ImageUtilities.readMBF(new URL("https://pbs.twimg.com/media/DpuaJrzUcAEeqTY.jpg"));
			DoGSIFTEngine engine = new DoGSIFTEngine();	
			LocalFeatureList<Keypoint> queryKeypoints = engine.findFeatures(query.flatten());
			LocalFeatureList<Keypoint> targetKeypoints = engine.findFeatures(target.flatten());
			RobustAffineTransformEstimator modelFitter = new RobustAffineTransformEstimator(5.0, 1500,
					  new RANSAC.PercentageInliersStoppingCondition(0.5));
			ConsistentLocalFeatureMatcher2d<Keypoint> matcher = new ConsistentLocalFeatureMatcher2d<Keypoint>(
					  new FastBasicKeypointMatcher<Keypoint>(8), modelFitter);
			matcher.setModelFeatures(queryKeypoints);
			matcher.findMatches(targetKeypoints);

			MBFImage consistentMatches = MatchingUtilities.drawMatches(query, target, matcher.getMatches(), 
			  RGBColour.RED);

			DisplayUtilities.display(consistentMatches);
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

Here was the error I got:
Exception in thread "main" java.lang.NoClassDefFoundError: jal/objects/BinaryPredicate
	at org.openimaj.knn.approximate.ByteNearestNeighboursKDTree.<init>(ByteNearestNeighboursKDTree.java:125)
	at org.openimaj.feature.local.matcher.FastBasicKeypointMatcher.setModelFeatures(FastBasicKeypointMatcher.java:134)
	at org.openimaj.feature.local.matcher.consistent.ConsistentLocalFeatureMatcher2d.setModelFeatures(ConsistentLocalFeatureMatcher2d.java:156)
	at imaj.ImajTester.main(ImajTester.java:235)
Caused by: java.lang.ClassNotFoundException: jal.objects.BinaryPredicate
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more

Was this a jar issue? Or it involves a cpp imlementation that I don't have in my system?

Best regards.

**Comment by jonhare** [comment]
You almost certainly do not have the jal jar on your class path. The only way you're going to fix this is by using maven or a similar build tool with automatic dependency management to correctly pull in all the dependencies and sub-dependencies.

**Comment by changbaishan** [comment]
According to the tutorial:L
First: mvn -DarchetypeGroupId=org.openimaj -DarchetypeArtifactId=openimaj-quickstart-archetype  -DarchetypeVersion=1.3.8  archetype:generate  <Success>

Second: mvn assembly:assembly

[INFO]
[INFO] --- maven-assembly-plugin:2.2.1:assembly (default-cli) @ openimaj-test-project ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.016 s
[INFO] Finished at: 2018-10-18T08:49:41-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2.1:assembly (default-cli) on project openimaj-test-project: Execution default-cli of goal org.apache.maven.plugins:maven-assembly-plugin:2.2.1:assembly failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.2.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-assembly-plugin:jar:2.2.1 -> org.apache.maven.shared:maven-common-artifact-filters:jar:1.3 -> org.apache.maven:maven-project:jar:2.0.8 -> org.apache.maven:maven-plugin-registry:jar:2.0.8: Failed to read artifact descriptor for org.apache.maven:maven-plugin-registry:jar:2.0.8: Failure to find org.apache.maven:maven:pom:2.0.8-el4j-20071205 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

Can you please advise how I am going to fix this issue?

Thanks very much.

**Comment by changbaishan** [comment]
Thank you very much! Dr. Hare.

Removing .m2 directory worked, although my other project damaged as a result. But I have been able to do
mvn assembly:assembly

After importing the project to eclipse, I am able to run the code. This time, ConsistentLocalFeatureMatcher2d was able to setModelFeatures. DisplayUtilities.display(consistentMatches); was a success. Although there was a warning:
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
Oct 18, 2018 1:23:04 PM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded C:\Users\chang\AppData\Local\Temp\jniloader3478545253028457704netlib-native_ref-win-x86_64.dll

I am very happy. Thanks again for your help and your patience.

Best regards,
Yong

**Comment by jonhare** [comment]
You can safely ignore that warning - it will fall back to a Java implementation of LAPACK
