### ISSUE TITLE
Simplest way to build "fat" OpenIMAJ jar for image recognition

### ISSUE THREAD

**Issue by stefan-reich** [openimaj/openimaj#156]
All I actually want is to use the HaarCascadeDetector.

I'm terrible with Maven and use my own build systems, so what I want is a complete jar supporting that class for JDK 10.

**Comment by jonhare** [comment]
Do this:

    git clone https://github.com/openimaj/openimaj.git
    cd openimaj
    mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true

that should be all thats needed.

**Comment by jonhare** [comment]
Ah, sorry, just realised I partially answered a different question. Doing the above will build openimaj from source and install locally. From that point create a minimal pom in a new directory that looks like this: 

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
      <modelVersion>4.0.0</modelVersion>
      <groupId>FatHaar</groupId>
      <artifactId>FatHaar</artifactId>
      <version>1.0-SNAPSHOT</version>
      <packaging>jar</packaging>
      <name>FatHaar</name>
      <properties>
        <openimaj.version>1.4-SNAPSHOT</openimaj.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
      </properties>
      <dependencies>
        <dependency>
          <groupId>org.openimaj</groupId>
          <artifactId>faces</artifactId>
          <version>${openimaj.version}</version>
          <scope>compile</scope>
        </dependency>
      </dependencies>
      <repositories>
        <repository>
          <id>openimaj-maven</id>
          <url>http://maven.openimaj.org/</url>
        </repository>
      </repositories>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>2.3.2</version>
            <configuration>
              <source>1.7</source>
              <target>1.7</target>
            </configuration>
          </plugin>
          <plugin>
            <artifactId>maven-assembly-plugin</artifactId>
            <version>2.2.1</version>
            <configuration>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </project>

and from within that directory run `mvn assembly:assembly` to generate the fat jar (in target/).

If you wanted to do the same from the precompiled artefacts on maven central, just change the openimaj version in the pom to 1.3.8

**Comment by stefan-reich** [comment]
I'm probably trying to roll my own algorithms now, but thanks a lot for this tutorial!
