### ISSUE TITLE
Could not find artifact vigna.dsi.unimi.it:jal:jar:20031117 in openimaj (http://maven.openimaj.org/)

### ISSUE THREAD

**Issue by ng1905** [openimaj/openimaj#167]
**Tested with org.openimaj faces v1.3.8 and v1.3.7**

Artifact vigna.dsi.unimi.it does no longer exist in maven central nor openimaj's own repository, making a maven build with openimaj impossible.

I came across this issue a few days ago. Without changing anything, my build process started to fail. After running `mvn dependency:tree --debug`, I saw that the missing artifact belongs to openimaj.

Full output:
```
[ERROR] Failed to execute goal on project oms-server: Could not resolve dependencies for project de.ngsger:oms-server:jar:0.16-SNAPSHOT: The following artifacts could not be resolved: vigna.dsi.unimi.it:jal:jar:20031117, net.sf.jafama:JaFaMa:jar:1.2, jgrapht:jgrapht:jar:0.8.2: Could not find artifact vigna.dsi.unimi.it:jal:jar:20031117 in openimaj (http://maven.openimaj.org/)
```

**Comment by jonhare** [comment]
Ok, I think I've fixed this now. Please let me know if it works for you, or if you run into further missing dependencies.

**Comment by ng1905** [comment]
First of all, thank you very much for the quick reply.

As far as I can tell, the dependencies issue is resolved **except** for `net.sf.jafama:JaFaMa:jar:1.2`, which still causes any builds to fail.

**Comment by jonhare** [comment]
Ok, sorry for the delay - that should be fixed too: http://maven.openimaj.org/net/sf/jafama/JaFaMa/1.2/JaFaMa-1.2.jar

**Comment by ng1905** [comment]
No problem at all. It seems like Github doesn't want to send me mail notifications either way, so I just saw your comment and tried it. Works like a charm, thanks for fixing this and maintaining the project :)
