### ISSUE TITLE
Missing artifact net.sf.qtjambi:qtjambi-platform-win32:jar:4.6.3.2

### ISSUE THREAD

**Issue by picca-ca** [openimaj/openimaj#172]
I have trying to install the package in both iMac and windows. all the same issue related to the same artifact. Please see the issue screen capture. Does that mean these code invalid now?

<img width="632" alt="issue" src="https://user-images.githubusercontent.com/54333759/65478651-b8717b80-de47-11e9-8a68-d2dfc9061a71.PNG">

**Comment by jonhare** [comment]
Try refreshing the project now - there was a misconfiguration that I've now fixed & those jars should all be available on maven.openimaj.org (e.g. http://maven.openimaj.org/net/sf/qtjambi/)

**Comment by picca-ca** [comment]
Hi Jonathon,
Thanks for your quick response. I re run the assembly, it still cound't find the four artifacts. Do I need to manually download them, or just rerun the build? Thanks

Dan

**Comment by picca-ca** [comment]
It seems the previous version is still in local cach, how do I enforce the update?

**Comment by picca-ca** [comment]
Hi Jonathon,

I create a new project and rebuild, still got the same error message. 
Failed to execute goal on project fr1: Could not resolve dependencies for project fr1:fr1:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: net.sf.qtjambi:qtjambi-base-mac64:jar:4.6.3.2, net.sf.qtjambi:qtjambi-platform-mac64:jar:4.6.3.2, org.openrdf.sesame:sesame:jar:2.6.4, uk.co.magus.fourstore:4store-client:jar:1.0: Failure to find net.sf.qtjambi:qtjambi-base-mac64:jar:4.6.3.2 in http://maven.openimaj.org/ was cached in the local repository, resolution will not be reattempted until the update interval of openimaj-maven has elapsed or updates are forced ->

**Comment by jonhare** [comment]
can you force-update? e.g. run `mvn -U compile` on the command line from the project directory?

**Comment by picca-ca** [comment]
I did mvn -U compile, still got the same error message.  Anything else I can do?

Warning message :  The POM for net.sf.qtjambi:qtjambi-platform-mac64:jar:4.6.3.2 is missing, no dependency information available

Error message: Could not resolve dependencies for project fr1:fr1:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: net.sf.qtjambi:qtjambi-base-mac64:jar:4.6.3.2, net.sf.qtjambi:qtjambi-platform-mac64:jar:4.6.3.2, org.openrdf.sesame:sesame:jar:2.6.4, uk.co.magus.fourstore:4store-client:jar:1.0: Could not find artifact net.sf.qtjambi:qtjambi-base-mac64:jar:4.6.3.2 in openimaj-maven (http://maven.openimaj.org/)

**Comment by jonhare** [comment]
Things seem more broken than I first thought... I'm just trying a build for myself on a clean machine, although I think I've almost definitely sorted the qtjambi dependencies (you should see them e.g. http://maven.ecs.soton.ac.uk/content/groups/maven.openimaj.org/net/sf/qtjambi/qtjambi-base-mac64/4.6.3.2/). Can you try the `mvn -U compile` command again & see if they go away now?

**Comment by picca-ca** [comment]
Yeah! I got the build successful.  Thank you very much !

Dan

**Comment by jonhare** [comment]
Ok, my clean build also worked now. I'll close this,  but feel free to reopen if something reoccurs.
