### ISSUE TITLE
Avoid aliasing when using homography model

### ISSUE THREAD

**Issue by changbaishan** [openimaj/openimaj#175]
Hi,

here is a code snippet for transforming image.

		String input = "https://pbs.twimg.com/media/D6MLG_zUYAAjVIv.jpg";
				try {
					MBFImage image = ImageUtilities.readMBF(new URL(input));
					int w = image.getWidth();
					int h = image.getHeight();
					MBFImage img = new MBFImage(w, h);
					int dis = 100;
					Pixel[] first = {new Pixel(0,0), new Pixel(w, 0), new Pixel(w, h), new Pixel(0, h)};
					Pixel[] second = {new Pixel(0,0), new Pixel(w, 0), new Pixel(w-dis, h), new Pixel(dis, h)};
					
					List<IndependentPair<Point2d,  Point2d>> data = new ArrayList<IndependentPair<Point2d, Point2d>>();
					for (int i = 0; i < first.length; i++) {
						IndependentPair ip = new IndependentPair(second[i], first[i]);
						data.add(ip);
					}
					Matrix mt = TransformUtilities.homographyMatrix(data);
					HomographyModel hm = new HomographyModel();					
					hm.setTransform(mt.inverse());
					//hm.estimate(data);
					//AffineTransformModel am = new AffineTransformModel();
					//am.estimate(data);
					for (int i = 0; i < w; i++) {
						for (int j = 0; j < h; j++) {
							Pixel p = new Pixel(i, j);
							Pixel p2 = (Pixel) hm.predict(p);
							img.setPixel(p2.x, p2.y, image.getPixel(p));
						}
					}
					
					DisplayUtilities.display(img);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

It works as intended except with serious aliasing as a by product. Can Prof. Hare enlighten me how to avoid the aliasing? 

Thanks very much.

**Comment by jonhare** [comment]
Use a `ProjectionProcessor` to do the mapping (it does something similar to what you're doing but with sub-pixel bilinear interpolation to avoid aliasing). See https://github.com/openimaj/openimaj/blob/master/demos/demos/src/main/java/org/openimaj/demos/image/SimpleMosaic.java to see it in action.

**Comment by changbaishan** [comment]
Hi Professor Hare,

Thank you for the interesting example. I will study it again my issue.

Best regards,

Yong
________________________________

**Comment by changbaishan** [comment]
Thank you very much! Professor Hare.

Here is the code I derived based on your example:


String input = "https://pbs.twimg.com/media/D6MLG_zUYAAjVIv.jpg";

 MBFImage image;
 try {
  image = ImageUtilities.readMBF(new URL(input));
  int w = image.getWidth();
  int h = image.getHeight();
  int dis = 100;
  Pixel[] first = {new Pixel(0,0), new Pixel(w, 0), new Pixel(w, h), new Pixel(0, h)};
  Pixel[] second = {new Pixel(0,0), new Pixel(w, 0), new Pixel(w-dis, h), new Pixel(dis, h)};
  List<IndependentPair<Point2d,  Point2d>> data = new ArrayList<IndependentPair<Point2d, Point2d>>();
  for (int i = 0; i < first.length; i++) {
   //IndependentPair ip = new IndependentPair(second[i], first[i]);
   IndependentPair ip = new IndependentPair(first[i], second[i]);
   data.add(ip);
  }
  Matrix mt = TransformUtilities.homographyMatrix(data);
  final ProjectionProcessor<Float[], MBFImage> ptp =
    new ProjectionProcessor<Float[], MBFImage>();
  MBFImage img = ptp.project(image, mt);
  DisplayUtilities.display(img);
 } catch (IOException e) {
  // TODO Auto-generated catch block
  e.printStackTrace();
 }

It worked out really well.

I really like OpenImaj.

Best regards,

Yong Liu
________________________________
