### ISSUE TITLE
Compiling from sources fails: Could not resolve dependencies for project org.openimaj.tools:SequenceFileTool:jar:1.4-SNAPSHOT

### ISSUE THREAD

**Issue by OscarVanL** [openimaj/openimaj#181]
I am following the guide to compile from sources here: https://github.com/openimaj/openimaj/wiki/Compiling-OpenIMAJ-from-Source

I run `mvn install -Dmaven.test.skip=true` as explained, but encounter this error and the compilation fails:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:37 min
[INFO] Finished at: 2019-10-20T22:36:25+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project SequenceFileTool: Could not resolve dependencies for project org.openimaj.tools:SequenceFileTool:jar:1.4-SNAPSHOT: Could not transfer artifact org.apache.hadoop:hadoop-hdfs:jar:2.0.0-cdh4.7.0 from/to openimaj-maven (http://maven.openimaj.org/): GET request of: org/apache/hadoop/hadoop-hdfs/2.0.0-cdh4.7.0/hadoop-hdfs-2.0.0-cdh4.7.0.jar from openimaj-maven failed: Connection reset -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :SequenceFileTool
```

It fails on the SequenceFileTool, looking at this: https://search.maven.org/artifact/org.openimaj.tools/SequenceFileTool/1.3.9/jar I suspect it might be related to this dependency entry:
	
```
<dependency>
		<groupId>org.apache.hadoop</groupId>
		<artifactId>hadoop-hdfs</artifactId>
		<version>2.0.0-cdh4.7.0</version>
</dependency>
```

This is because the quoted groupId (https://search.maven.org/search?q=org.apache.hadoop) has no artifact called `hadoop-hdfs`, which would explain the GET request failure.

**Comment by jonhare** [comment]
that artefact should be  available here: http://maven.ecs.soton.ac.uk/content/groups/maven.openimaj.org/org/apache/hadoop/hadoop-hdfs/2.0.0-cdh4.7.0/

transient networking issue?

**Comment by OscarVanL** [comment]
I did try the compilation twice and had the same error, however, I'll give it another try through the University's VPN in case it's some strange Virgin Media oddity.

Also, apologies for disturbing you at this late hour (and on the weekend!) - I didn't expect a reply so soon!

**Comment by OscarVanL** [comment]
Build success! :)
