### ISSUE TITLE
missing java sources

### ISSUE THREAD

**Issue by jurgenvdw23** [openimaj/openimaj#185]
I pull the latest (10 Jan 2020)
Some of the missing:
org.openimaj.util.array.ArrayUtils
org.openimaj.ml.clustering.FloatCentroidsResult;
org.openimaj.ml.clustering.assignment.hard.ExactFloatAssigner;
org.openimaj.ml.clustering.kmeans.FloatKMeans;
org.openimaj.feature.DoubleFV;
org.openimaj.feature.DoubleFVComparison;

many more

**Comment by jonhare** [comment]
These aren't missing; they're generated automatically as part of the build process by the maven jtemp plugin from the jtemp templates (e.g. https://github.com/openimaj/openimaj/blob/master/core/core/src/main/jtemp/org/openimaj/util/array/ArrayUtils.jtemp)

**Comment by jurgenvdw23** [comment]
Thanks - The only problem now is that the maven plugin can not be installed in eclipse, checksum error, although cmd line mvn does work - sort of.

**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project core-feature: Compilation failure: Compilation failure:
[ERROR] \git\openimaj\core\core-feature\target\generated-sources\jtemp\org\openimaj\feature\ByteFV.java:[51,7] error: cannot access DoubleFV**

eclipse plugin fail:
An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Problems downloading artifact: osgi.bundle,uk.ac.soton.ecs.jsh2.m2e.jtemp,1.2.1.
MD5 hash is not as expected. Expected: d8e4a0e5a90ec7e96f191f3047ed026e and found b7f443b1e4d7315e703ad8b2f7b3355f.
Problems downloading artifact: org.eclipse.update.feature,uk.ac.soton.ecs.jsh2.m2e.jtemp.feature,1.2.1.
MD5 hash is not as expected. Expected: f316ec8d44ecfe615187c0d6526c3904 and found f27120d8f7baabe66c87b414a77f3af2.

**Comment by jonhare** [comment]
I'll have to look into what's up with eclipse... 

Can you describe what you ran on the command line & from what directory?

**Comment by jurgenvdw23** [comment]
I did a clone to a folder and then run mvn install -DskipTests
using Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
or just running it in core subdir (generates lots of errors)

https://marketplace.eclipse.org/content/m2e-jtemp
Fails in photon and jee-2019-12
