### ISSUE TITLE
Can't resolve dependencies

### ISSUE THREAD

**Issue by natfatykhova** [openimaj/openimaj#186]
Hello,
Looks like some of dependencies are broken:
![image](https://user-images.githubusercontent.com/48601930/72610651-d8a9d680-391f-11ea-8d89-d3b02132614d.png)

It was ok last week, probably something changed just recently.

Thx

**Comment by natfatykhova** [comment]
Fixed by using whole library instead of components
`compile group: 'org.openimaj', name: 'openimaj', version: '1.3.9', ext: 'pom'`

**Comment by jurgenvdw23** [comment]
sorry for the delay (I was on leave)
I can confirm that it now compiles successfully
