### ISSUE TITLE
Please remove DisplayUtilities.display(image, "" + bpp); from SharpPixelProportion 

### ISSUE THREAD

**Issue by changbaishan** [openimaj/openimaj#300]
In org.openimaj.image.feature.global.SharpPixelProportion, there is a DisplayUtilities.display(image, "" + bpp); line. This line causes unintended display when executing the said object. 

Also, I hope all openimj developers are free from covid. Please accept my best regards.

**Comment by jonhare** [comment]
whoops! just removed :)
