### ISSUE TITLE
High CPU usage by OpenIMAJGrabber

### ISSUE THREAD

**Issue by craigraw** [openimaj/openimaj#309]
I'm using the sarxos webcam-capture project with the default driver which uses OpenIMAJGrabber internally. My use case is scanning QR codes, so I don't need a high FPS - in fact 10 FPS is sufficient.

Nevertheless, I'm experiencing high CPU usage (1 core at 100%) with this approach. I've taken a good look at the Java side of things and can't find the issue there. Rather it seems like calling the `OpenIMAJGrabber::nextFrame()` method causes the CPU to run in a tight loop. I'm experiencing this issue on OSX, Windows and Linux.

Is there anything that can be done to reduce this load? Other native camera applications do not seem to have this issue, even at much higher capture frame rates.

**Comment by jonhare** [comment]
I can’t replicate using just OpenIMAJ code - with OpenIMAJ’s VideoDisplay class I get under 25% cpu utilisation of a single core at ~30FPS (which isn’t great, but there is a considerable amount of data conversion going on so is understandable); the only way for `OpenIMAJGrabber::nextFrame()` to be eating CPU cycles is if its being called too frequently - perhaps the webcam-capture project doesn’t implement sleeping, or your code isn’t sleeping between frames?

Note that internally the frame rate passed to OpenIMAJGrabber is only a hint to the OS to be ready to deliver frames at the specified rate; it’s the user code on the java side that determines how frequently to ask the native code for the next frame...

On 7 Apr 2021, at 09:54, craigraw ***@***.******@***.***>> wrote:

CAUTION: This e-mail originated outside the University of Southampton.


I'm using the sarxos webcam-capture project with the default driver which uses OpenIMAJGrabber internally. My use case is scanning QR codes, so I don't need a high FPS - in fact 10 FPS is sufficient.

Nevertheless, I'm experiencing high CPU usage (1 core at 100%) with this approach. I've taken a good look at the Java side of things and can't find the issue there. Rather it seems like calling the OpenIMAJGrabber::nextFrame() method causes the CPU to run in a tight loop. I'm experiencing this issue on OSX, Windows and Linux.

Is there anything that can be done to reduce this load? Other native camera applications do not seem to have this issue, even at much higher capture frame rates.

**Comment by craigraw** [comment]
Thanks - further investigation proved that the webcam-capture project has several tight loops (in WebcamDefaultDriver and WebcamProcessor). I've added `Thread.sleep(100)` to both of these and CPU usage has reduced. It's still higher than what I'd like, but it's an improvement!

Closing this off.
