### ISSUE TITLE
calculateOrientatedBoundingBox is not properly rotated 

### ISSUE THREAD

**Issue by HaleB** [openimaj/openimaj#81]
The bounding box calculated by the function below is off by 90 degrees.

RotatedRectangle r = comp.calculateOrientatedBoundingBox();

Details:
ConnectedComponent comp;
...
Polygon p = comp.toPolygon();
outImage.drawShape(p, RGBColour.BLUE); //Shape overlays image correctly
RotatedRectangle r = comp.calculateOrientatedBoundingBox();
outImage.drawShape(r, RGBColour.RED); //red box is not correct
r.rotation += Math.PI / 2;
outImage.drawShape(r, RGBColour.GREEN); //Green bounding box is correct

Let me know if you need any additional info to reproduce.

**Comment by jonhare** [comment]
Sees like the height/width were being transposed by the RotatingCalipers. Should be fixed in commit 601b5bb43b0cb24d4a827fbe2358a11e52889ea1 (with accompanying unit tests).

**Comment by HaleB** [comment]
Thanks - will test it out
