### ISSUE TITLE
Rectangle.isInside returning reverse of what it should

### ISSUE THREAD

**Issue by bisoldi** [openimaj/openimaj#89]
If I am reading it correctly, Rectangle.isInside(Rectangle that) is supposed to see if the rectangle represented by the object who's isInside method is being called is inside of the Rectangle represented by 'that'.  

If so, the logic within that method reports true for the opposite ('that' is inside 'this').  

I believe if you either reverse all of the mathematical operators or swap all references to 'this' and 'that' in the logic, it will fix it.

**Comment by jonhare** [comment]
I think its probably a documentation issue rather than a code issue. I'd propose changing the documentation to read "Test if the given rectangle is inside this one.". The method would still be consistent with `isInside(Point2d)` that way. Thoughts?

**Comment by bisoldi** [comment]
Ah, I see.  I didn't think to check the other methods to see if they maintained the same logic.  

In my mind, I read true/false methods as being asked of the object the method is called on, so the  "this.isInside(that)" (checking to see if this is inside of that) is natural to me.  If time were not a scarce resource, I would suggest changing the method name to something like surrounds() or doesSurround(), however I imagine that might be quite difficult if the IDE doesn't refactor it perfectly.  In my application, I am wrapping around DetectedFace and wrote the convenience methods isInside and doesSurround in the exact same way (this.doesSurround(that) and this.isInside(that)).

End of the day, it's just semantics, both ways would work equally well!

Thank you for clarifying!

**Comment by jonhare** [comment]
Agreed re. the semantics, but it would be a rather big change (and might break other peoples code). I've fixed the documentation in f11c376 and for the time being will close this issue.
