### ISSUE TITLE
Building your own classifier tutorial

### ISSUE THREAD

**Issue by asaladino** [openimaj/openimaj#92]
Does anyone know if there is a tutorial on building your own classifier? I'm trying to work backwards through the sample that uses 
```
Caltech101.getData(ImageUtilities.FIMAGE_READER); 
```
however there seems to be these matlab files bundled with the images and I'm not sure of there purpose.  A simple tutorial would be very helpful. I'm hoping that creating a classifier in openimaj will be much faster than opencv.

**Comment by jonhare** [comment]
Have you looked at this: http://www.openimaj.org/tutorial/classification101.html ?

With respect to the Caltech101 dataset the matlab files contain the bounding boxes and bounding polygons of the object in the image. In the above tutorial they are not used though (only the images and labels are used).

**Comment by asaladino** [comment]
I have looked at that page but all the heavy lifting was done by Caltech101.getData(ImageUtilities.FIMAGE_READER). This method/class downloads a prepackaged archive with all the sample images nicely sized and some sort of annotation mat files. I want to know how to create a similar package so I can find my own objects. Do you have any suggestions on how to make these annotation mat files? There seems to be a few classes that make this happen but I'm not sure exactly what they do or how to properly use them:
```
MatFileWriter
```
Which takes an array of:
```
List<MLArray> data = new ArrayList();
```
Which seems to have something to do with:
```
FloatFV
MLDouble
```
Any assistance would be much appreciated.

**Comment by jonhare** [comment]
Just ignore the Matlab/annotation stuff completely - it's not needed for classification and is specific to the Caltech 101 dataset. All you need to do is create something that will provide a `GroupedDataset` in which the keys are the image classes and the values are `ListDataset`s which hold the images (or objects that can provide access to each image).

In the simplest case, you could arrange all your images into a set of folders on disk, with one folder for each class. You could then use a `VFSGroupedDataset` directly to provide the data (see the tutorial chapter on datasets - http://www.openimaj.org/tutorial/image-datasets.html).

**Comment by asaladino** [comment]
Oh, interesting. So I can do something like this:
```
VFSGroupDataset<FImage> allData = new VFSGroupDataset("/my/positive/images/", ImageUtilities.FIMAGE_READER);
GroupedDataset<String, ListDataset<Record<FImage>>, Record<FImage>> data = GroupSampler.sample((ReadableGroupDataset)allData, 5, false);
```
And cast it as a ReadableGroupDataset. I'll try it this weekend.

I'll also have to reread the classification page because it seems like a different process from opencv. The openImag classifier training seems to only require positive images where as with opencv you need positive, negative, and generated sample images (and a lot of time).

**Comment by jonhare** [comment]
Not quite - you need both positive and negative (or class1; class2; class3; ... for multi-class problems like the example with Caltech101 which has 101 classes). Assume you have a directory structure like this: 

    /my/images/positive
    /my/images/negative

Then you would construct a dataset like this:

    VFSGroupDataset<FImage> allData = new VFSGroupDataset("/my/images/", ImageUtilities.FIMAGE_READER);

and the "keys" of that dataset would be "positive" and "negative".

**Comment by asaladino** [comment]
I think I follow, I'll need to play around with it. So, when I evaluate an image with the classifier I'll look at the "positive" key/class matches. I like this approach then I can have different classes of positive and negative images.

Can you tell me what class to look at for saving and loading trained BatchAnnotator's to file? Can I use the IOUtils.writeToFile?

**Comment by jonhare** [comment]
Yes, `IOUtils.writeToFile` should work.

**Comment by asaladino** [comment]
Excellent. Thanks for your help, you have created an impressive library.
