### ISSUE TITLE
Training Haar Cascades

### ISSUE THREAD

**Issue by asaladino** [openimaj/openimaj#93]
I noticed in the HaarCascadeDetector class there is a note "The set of pre-trained cascades from OpenCV." Did you use opencv cascades because they are difficult to build? Is there a process in OpenIMAJ to train a Haar Cascade or is opencv_traincascade the only means to create one?

Thanks for you help.

**Comment by jonhare** [comment]
The inbuilt training code isn't currently complete & unfortunately the code that runs the cascades is currently only compatible with the old style OpenCV cascades, but not the format produced by the newer OpenCV tools (which are **much** faster than the old tools).

**Comment by asaladino** [comment]
Nice, I was hoping there might be one in the works. Are you in need of testers beyond your unit testing? I'd be interested in assisting and learning the logic and math behind the these imaging techniques. Also, I didn't see any tags or branches for the new version, are the changes currently in a local repo?

**Comment by jonhare** [comment]
Pretty much all incomplete and half-baked features are in the sandbox project at the moment (largely as a result of feature branches being a bit of a pain when the code was in subversion [and CVS before that!]). 

The bit you're looking for is here: https://github.com/openimaj/openimaj/tree/master/demos/sandbox/src/main/java/org/openimaj/image/objectdetection/haar/training

I haven't looked at it for a couple of years, but if I remember correctly the training of ensembles of classifier trees and stumps is complete, but the training of cascades is not.

**Comment by asaladino** [comment]
Thanks for the information. I looked over the source and I am unfamiliar with many of concepts so I'll have to stick with opencv training. Thanks for your help.
