### ISSUE TITLE
MBFImage.flattenMax() has a bug in calculation

### ISSUE THREAD

**Issue by hsq125** [openimaj/openimaj#98]
Hello guys!

I think there is a bug in the implementation of the **MBFImage.flattenMax()** method. I'm using version **1.3.1**.

Line 185:
					```if (max > (this.bands.get(i)).pixels[y][x])```
should be
					```if (max < (this.bands.get(i)).pixels[y][x])```

It actually computes the flattenMin(). Or Am I wrong?

Thanks a lot (for this excellent library :) )

**Comment by jonhare** [comment]
Yes, you appear to be correct. Fixed in aaf632aa.

**Comment by hsq125** [comment]
Good :+1: 
Thanks a lotç
